#===============================================================================
# Section 6: Assemble DOCX Report (figures + tables + explanations)
#===============================================================================
print("--- Starting Section 6: Assemble DOCX Report ---")

dir.create(CONFIG$output_dir, showWarnings = FALSE, recursive = TRUE)
report_rmd_path <- output_path("analysis_report.Rmd")
report_docx_path <- output_path("analysis_report.docx")

report_lines <- c(
  "---",
  "title: \"BNP to NT-proBNP Substudy Report\"",
  "output:",
  "  word_document:",
  "    toc: true",
  "    number_sections: true",
  "params:",
  sprintf("  output_dir: \"%s\"", CONFIG$output_dir),
  "---",
  "",
  "```{r setup, include=FALSE}",
  "knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, fig.align = 'center', fig.width = 6.5, fig.height = 6.5, out.width = '100%')",
  "suppressPackageStartupMessages({",
  "  library(dplyr)",
  "  library(readr)",
  "  library(ggplot2)",
  "  library(gtsummary)",
  "  library(modelsummary)",
  "  library(knitr)",
  "  library(flextable)",
  "})",
  "dir.create(params$output_dir, showWarnings = FALSE, recursive = TRUE)",
  "get_obj <- function(name) {",
  "  if (exists(name, envir = knitr::knit_global())) {",
  "    get(name, envir = knitr::knit_global())",
  "  } else {",
  "    NULL",
  "  }",
  "}",
  "set_na_str_safe <- function(ft, na_str = '') {",
  "  if (is.null(ft)) {",
  "    return(ft)",
  "  }",
  "  ns_exports <- tryCatch(getNamespaceExports('flextable'), error = function(e) character(0))",
  "  if ('na_str' %in% ns_exports) {",
  "    return(flextable::na_str(ft, na_str = na_str))",
  "  }",
  "  if ('set_na_str' %in% ns_exports) {",
  "    return(flextable::set_na_str(ft, na_str = na_str))",
  "  }",
  "  ft",
  "}",
  "format_table <- function(df, caption, digits = 2, font_size = 9, drop_model_type = TRUE) {",
  "  if (drop_model_type && 'model_type' %in% names(df)) {",
  "    df <- dplyr::select(df, -model_type)",
  "  }",
  "  if (any(c('part', '.part') %in% names(df))) {",
  "    df <- dplyr::select(df, -dplyr::any_of(c('part', '.part')))",
  "  }",
  "  df <- df %>%",
  "    dplyr::rename_with(~ gsub('^\\\\.', '', .x)) %>%",
  "    dplyr::rename_with(~ gsub('_', ' ', .x)) %>%",
  "    dplyr::rename_with(~ gsub('\\\\.', ' ', .x))",
  "  pval_cols <- grep('p\\\\.value|p value|p-value', names(df), ignore.case = TRUE, value = TRUE)",
  "  numeric_cols <- names(df)[vapply(df, is.numeric, logical(1))]",
  "  round_cols <- setdiff(numeric_cols, pval_cols)",
  "  if (length(round_cols) > 0) {",
  "    df <- dplyr::mutate(df, dplyr::across(all_of(round_cols), ~ round(.x, digits)))",
  "  }",
  "  ft <- flextable::flextable(df)",
  "  ft <- flextable::set_caption(ft, caption = caption)",
  "  ft <- flextable::fontsize(ft, size = font_size, part = 'all')",
  "  ft <- flextable::autofit(ft)",
  "  ft <- set_na_str_safe(ft, na_str = '')",
  "  ft",
  "}",
  "add_reference_row <- function(tbl, model, var, term_col = 'term', ref_label = NULL, digits = 2) {",
  "  if (!is.data.frame(tbl) || is.null(model)) {",
  "    return(tbl)",
  "  }",
  "  mf <- tryCatch(model.frame(model), error = function(e) NULL)",
  "  if (is.null(mf) || !(var %in% names(mf))) {",
  "    return(tbl)",
  "  }",
  "  var_data <- mf[[var]]",
  "  if (!is.factor(var_data) || length(levels(var_data)) < 1) {",
  "    return(tbl)",
  "  }",
  "  ref_level <- levels(var_data)[1]",
  "  if (is.null(ref_label)) {",
  "    ref_label <- paste0(var, ': ', ref_level, ' (ref)')",
  "  }",
  "  if (!(term_col %in% names(tbl))) {",
  "    return(tbl)",
  "  }",
  "  estimate_label <- sprintf('%.*f [%.*f, %.*f]', digits, 1, digits, 1, digits, 1)",
  "  ref_row <- as.list(rep(NA, ncol(tbl)))",
  "  names(ref_row) <- names(tbl)",
  "  ref_row[[term_col]] <- ref_label",
  "  estimate_cols <- grep('estimate', names(tbl), ignore.case = TRUE, value = TRUE)",
  "  if (length(estimate_cols) > 0) {",
  "    ref_row[estimate_cols] <- estimate_label",
  "  }",
  "  p_cols <- grep('p\\\\.value|p value|p-value', names(tbl), ignore.case = TRUE, value = TRUE)",
  "  if (length(p_cols) > 0) {",
  "    ref_row[p_cols] <- NA_real_",
  "  }",
  "  term_vals <- tbl[[term_col]]",
  "  if (is.factor(term_vals)) {",
  "    term_vals <- as.character(term_vals)",
  "  }",
  "  var_rows <- which(grepl(paste0('^', var), term_vals))",
  "  if (length(var_rows) > 0) {",
  "    insert_after <- var_rows[1] - 1",
  "  } else {",
  "    intercept_rows <- which(grepl('intercept', tolower(term_vals)))",
  "    insert_after <- if (length(intercept_rows) > 0) intercept_rows[1] else 0",
  "  }",
  "  if (insert_after <= 0) {",
  "    tbl <- dplyr::bind_rows(ref_row, tbl)",
  "  } else if (insert_after >= nrow(tbl)) {",
  "    tbl <- dplyr::bind_rows(tbl, ref_row)",
  "  } else {",
  "    tbl <- dplyr::bind_rows(",
  "      tbl[seq_len(insert_after), , drop = FALSE],",
  "      ref_row,",
  "      tbl[(insert_after + 1):nrow(tbl), , drop = FALSE]",
  "    )",
  "  }",
  "  tbl",
  "}",
  "page_break <- function() knitr::asis_output('\\\\pagebreak')",
  "filter_protocol_metrics <- function(df) {",
  "  if (!all(c('.metric', '.estimator') %in% names(df))) {",
  "    return(df)",
  "  }",
  "  allowed <- c(",
  "    'pearson_r_log10', 'rsq_log10', 'rmse_log10',",
  "    'weighted_kappa_quadratic',",
  "    'sens', 'spec', 'ppv', 'npv',",
  "    'ols_intercept_log10', 'ols_slope_log10',",
  "    'paba_intercept_log10', 'paba_intercept_lower_log10', 'paba_intercept_upper_log10',",
  "    'paba_slope_log10', 'paba_slope_lower_log10', 'paba_slope_upper_log10'",
  "  )",
  "  df <- dplyr::filter(df, .metric %in% allowed)",
  "  df <- dplyr::filter(df, !(.metric %in% c('sens','spec','ppv','npv') & .estimator != 'binary'))",
  "  df <- dplyr::filter(df, !(.metric %in% c('weighted_kappa_quadratic') & .estimator != 'weighted'))",
  "  df <- dplyr::filter(df, !(.metric %in% c('ols_intercept_log10','ols_slope_log10') & .estimator != 'OLS_log10'))",
  "  df <- dplyr::filter(df, !(.metric %in% c('paba_intercept_log10','paba_intercept_lower_log10','paba_intercept_upper_log10','paba_slope_log10','paba_slope_lower_log10','paba_slope_upper_log10') & .estimator != 'PaBa_log10'))",
  "  df <- dplyr::filter(df, !(.metric %in% c('pearson_r_log10') & .estimator != 'log10'))",
  "  df <- df %>%",
  "    dplyr::mutate(.metric = factor(.metric, levels = allowed)) %>%",
  "    dplyr::arrange(.metric, .estimator)",
  "  df",
  "}",
  "```",
  "",
  "# Overview",
  "This report compiles the figures and tables produced by the analysis script and describes how each output corresponds to the published protocol.",
  "",
  "# Baseline Characteristics",
  "Baseline characteristics are summarized for the initial cohort (Table 1).",
  "",
  "```{r table-baseline}",
  "baseline_table_final <- get_obj('baseline_table_final')",
  "if (!is.null(baseline_table_final)) {",
  "  baseline_table_final <- baseline_table_final %>%",
  "    gtsummary::modify_caption('Baseline characteristics of the initial cohort.')",
  "  ft <- gtsummary::as_flex_table(baseline_table_final)",
  "  ft <- flextable::fontsize(ft, size = 8, part = 'all')",
  "  ft <- flextable::autofit(ft)",
  "  ft",
  "} else {",
  "  cat('Baseline table not available in memory.\\n')",
  "}",
  "```",
  "\\pagebreak",
  "",
  "# Primary Analysis: Kasahara Conversion Formula",
  "The Kasahara formula was applied to BNP values to predict NT-proBNP. Agreement between measured and predicted values is summarized below.",
  "",
  "## Model definition, equation, and interpretation",
  "The Kasahara conversion is an externally derived linear regression on the log10 scale that predicts the median NT-proBNP from BNP and covariates. Variables: BNP and NT-proBNP are in pg/mL; Age in years; BMI in kg/m^2; Hb_gdl in g/dL; CrCl in mL/min; Sex_M = 1 for male and 0 for female; AF = 1 if atrial fibrillation is present.",
  "",
  "The published equation implemented here is:",
  "$$",
  "\\log_{10}(\\widehat{NTproBNP}) =",
  "2.05 + 0.907 \\log_{10}(BNP) - 0.00522 Age + 0.00283 BMI - 0.00866 Hb_{gdl} + f(CrCl) + 0.0164(1 - Sex_M) + 0.194 AF",
  "$$",
  "with the creatinine clearance spline term",
  "$$",
  "f(CrCl) =",
  "-0.0422 CrCl + 0.000530 CrCl^2 - 0.00000214 CrCl^3",
  "- 0.00000278 \\max(0, CrCl - k_1)^3",
  "+ 0.00000621 \\max(0, CrCl - k_2)^3",
  "- 0.00000133 \\max(0, CrCl - k_3)^3",
  "$$",
  "and knots $k_1=56.5$, $k_2=72.4$, $k_3=93.7$ (mL/min). Let $\\eta$ be the right-hand side of the log10 equation above; the median predicted NT-proBNP on the original scale is $\\widehat{NTproBNP}_{median} = 10^{\\eta}$.",
  "",
  "## Calibration and method-comparison regressions",
  "Two calibration regressions are used to quantify bias:",
  "",
  "1) Original-scale calibration (OLS) used in the calibration plots:",
  "$$",
  "NTproBNP = a + b \\times \\widehat{NTproBNP}",
  "$$",
  "",
  "2) Log-log recalibration (OLS and Passing-Bablok):",
  "$$",
  "\\log_{10}(NTproBNP) = I + S \\times \\log_{10}(\\widehat{NTproBNP}_{Kasahara})",
  "$$",
  "and the recalibrated prediction is",
  "$$",
  "\\widehat{NTproBNP}_{recal} = 10^{I + S \\log_{10}(\\widehat{NTproBNP}_{Kasahara})}.",
  "$$",
  "",
  "Passing-Bablok regression is a robust, nonparametric method-comparison regression of the form $y = a + b x$ that is less sensitive to outliers and measurement error. The intercept ($a$) represents constant bias; the slope ($b$) represents proportional bias.",
  "",
  "## Interpretation and rationale",
  "A slope of 1 and intercept of 0 indicate perfect calibration; deviations quantify systematic over- or underestimation. Log-log recalibration is used because both biomarkers are right-skewed and multiplicative errors are expected on the original scale.",
  "",
  "```{r table-kasahara-metrics}",
  "kasahara_metrics_path <- file.path(params$output_dir, 'kasahara_model_prediction_errors.rds')",
  "if (file.exists(kasahara_metrics_path)) {",
  "  kasahara_metrics <- readr::read_rds(kasahara_metrics_path)",
  "  kasahara_metrics <- filter_protocol_metrics(kasahara_metrics)",
  "  format_table(",
  "    kasahara_metrics,",
  "    'Kasahara model performance metrics (includes RMSE, R-squared, and OLS/PaBa calibration slope/intercept).',",
  "    digits = 2,",
  "    font_size = 8",
  "  )",
  "} else {",
  "  cat('Kasahara metrics file not found.\\n')",
  "}",
  "```",
  "\\pagebreak",
  "",
  "```{r fig-kasahara-cal-log, fig.cap='Kasahara model calibration plot (log scale).'}",
  "knitr::include_graphics(file.path(params$output_dir, 'calibration_plot_kasahara_log.png'))",
  "```",
  "\\pagebreak",
  "",
  "```{r fig-kasahara-cal-lin, fig.cap='Kasahara model calibration plot (linear scale).'}",
  "knitr::include_graphics(file.path(params$output_dir, 'calibration_plot_kasahara_lin.png'))",
  "```",
  "\\pagebreak",
  "",
  "```{r fig-kasahara-ba-rel, fig.cap='Kasahara model Bland-Altman plot (relative error).'}",
  "knitr::include_graphics(file.path(params$output_dir, 'BA_kasahara_relative.png'))",
  "```",
  "\\pagebreak",
  "",
  "```{r fig-kasahara-ba-abs, fig.cap='Kasahara model Bland-Altman plot (absolute error).'}",
  "knitr::include_graphics(file.path(params$output_dir, 'BA_kasahara_absolute.png'))",
  "```",
  "\\pagebreak",
  "",
  "# Updated Conversion Formula (Recalibrated Model)",
  "A new model was fit on log-transformed NT-proBNP with the specified predictors and interactions. Passing-Bablok regression (bootstrap) was used for recalibration.",
  "",
  "## New model equation (OLS on log10 scale)",
  "The conversion model is an ordinary least squares regression on log10(NT-proBNP) with restricted cubic splines (rcs) and interactions (matching the Kasahara model scale). The model fit in code is:",
  "$$",
  "\\log_{10}(NTproBNP) =",
  "b_0 + rcs(Age,3) * rcs(CrCl,3) * rcs(\\log_{10}(BNP),3)",
  "+ b_{Sex} Sex_M + rcs(BMI,3) + b_{AF} AF + rcs(Hb_{gdl},3) + e",
  "$$",
  "The `*` operator expands to all lower-order interactions among the spline bases for Age, CrCl, and log10(BNP). This specification allows the BNP-to-NT-proBNP relationship to vary nonlinearly by age and renal function.",
  "",
  "Predicted values on the original scale are obtained by back-transforming the fitted linear predictor:",
  "$$",
  "\\widehat{NTproBNP}_{median} = 10^{\\widehat{\\eta}}",
  "$$",
  "If a mean prediction is required under a log-normal error model, the mean is",
  "$$",
  "\\widehat{NTproBNP}_{mean} = 10^{\\widehat{\\eta} + \\sigma^2 \\ln(10)/2},",
  "$$",
  "where $\\sigma$ is the residual standard error on the log10 scale.",
  "",
  "An intercept-only null model, $\\log(NTproBNP)=b_0$, is compared with the full model to summarize incremental fit (AIC/BIC and likelihood-based diagnostics).",
  "",
  "## Recalibration regressions",
  "The fitted linear predictor is recalibrated using Passing-Bablok regression on the log10 scale (per protocol):",
  "$$",
  "\\log_{10}(NTproBNP) = I + S \\times \\log_{10}(\\widehat{NTproBNP}_{initial})",
  "$$",
  "so that",
  "$$",
  "\\widehat{NTproBNP}_{recal,median} = 10^{I + S \\times \\log_{10}(\\widehat{NTproBNP}_{initial}))}.",
  "$$",
  "The recalibration parameters $I$ and $S$ are the bootstrap-median intercept and slope from the log10-log10 Passing-Bablok regression.",
  "",
  "## Interpretation and rationale",
  "OLS is used for model fitting because it estimates the conditional mean on the log10 scale and yields closed-form predictions. Splines capture nonlinearities without imposing a rigid functional form, and the interaction structure reflects effect modification by age and renal function. Recalibration adjusts for any systematic bias when applying the model to the study cohort; $I=0$ and $S=1$ indicate perfect calibration. The log10 scale is used consistently to match the Kasahara model.",
  "",
  "```{r table-paba-boot}",
  "paba_boot_path <- file.path(params$output_dir, 'paba_log10_bootstrap_summary.rds')",
  "if (file.exists(paba_boot_path)) {",
  "  paba_boot <- readr::read_rds(paba_boot_path)",
  "  format_table(",
  "    paba_boot,",
  "    'Bootstrapped Passing-Bablok calibration (log10 scale).',",
  "    digits = 4,",
  "    font_size = 8",
  "  )",
  "} else {",
  "  cat('Bootstrapped Passing-Bablok summary not found.\\n')",
  "}",
  "```",
  "\\pagebreak",
  "",
  "```{r table-newmodel-metrics}",
  "newmodel_metrics_path <- file.path(params$output_dir, 'apparent_performance_new_model.rds')",
  "if (file.exists(newmodel_metrics_path)) {",
  "  newmodel_metrics <- readr::read_rds(newmodel_metrics_path)",
  "  newmodel_metrics <- filter_protocol_metrics(newmodel_metrics)",
  "  format_table(",
  "    newmodel_metrics,",
  "    'Apparent performance metrics for the recalibrated model (median prediction, PaBa recalibration).',",
  "    digits = 2,",
  "    font_size = 8",
  "  )",
  "} else {",
  "  cat('New model performance file not found.\\n')",
  "}",
  "```",
  "\\pagebreak",
  "",
  "```{r table-newmodel-optimism}",
  "optimism_path <- file.path(params$output_dir, 'optimism_corrected_estimates_new_model.rds')",
  "if (file.exists(optimism_path)) {",
  "  optimism_tbl <- readr::read_rds(optimism_path)",
  "  optimism_tbl <- filter_protocol_metrics(optimism_tbl)",
  "  format_table(",
  "    optimism_tbl,",
  "    'Optimism-corrected performance metrics (bootstrap, PaBa recalibration).',",
  "    digits = 2,",
  "    font_size = 8",
  "  )",
  "} else {",
  "  cat('Optimism-corrected metrics file not found.\\n')",
  "}",
  "```",
  "\\pagebreak",
  "",
  "Bias-corrected calibration is shown below using `rms::calibrate` (log10 scale).",
  "",
  "```{r fig-new-cal-bias, fig.cap='Bias-corrected calibration curve (bootstrap, log10 scale).'}",
  "knitr::include_graphics(file.path(params$output_dir, 'calibration_curve_new_model_bias_corrected_log10.png'))",
  "```",
  "\\pagebreak",
  "",
  "```{r fig-new-cal-log, fig.cap='Recalibrated model calibration plot (log scale).'}",
  "knitr::include_graphics(file.path(params$output_dir, 'calibration_plot_new_model_log.png'))",
  "```",
  "\\pagebreak",
  "",
  "```{r fig-new-cal-lin, fig.cap='Recalibrated model calibration plot (linear scale).'}",
  "knitr::include_graphics(file.path(params$output_dir, 'calibration_plot_new_model_lin.png'))",
  "```",
  "\\pagebreak",
  "",
  "```{r fig-new-ba-rel, fig.cap='Recalibrated model Bland-Altman plot (relative error).'}",
  "knitr::include_graphics(file.path(params$output_dir, 'BA_new_model_relative.png'))",
  "```",
  "\\pagebreak",
  "",
  "```{r fig-new-ba-abs, fig.cap='Recalibrated model Bland-Altman plot (absolute error).'}",
  "knitr::include_graphics(file.path(params$output_dir, 'BA_new_model_absolute.png'))",
  "```",
  "\\pagebreak",
  "",
  "```{r fig-new-paba, fig.cap='Passing-Bablok regression for recalibrated model (measured vs predicted).'}",
  "knitr::include_graphics(file.path(params$output_dir, 'paba_plot_new_model.png'))",
  "```",
  "\\pagebreak",
  "",
  "# Secondary Analysis: Outcome Associations",
  "Logistic regression models evaluate associations between biomarker categories and the 30-day composite outcome.",
  "",
  "## Logistic regression models (categorical predictors)",
  "The composite outcome is defined as 1 if MINS30 == 1 or vascular_death == 1, and 0 otherwise. For each categorical biomarker, we fit:",
  "$$",
  "\\operatorname{logit}\\{P(outcome=1)\\} = a_0 + \\sum_{j=2}^{4} a_j \\; I(Category=j)",
  "$$",
  "where the reference category is <100 pg/mL and the remaining categories are 100-<200, 200-<1500, and >=1500. Models are:",
  "",
  "- Model A: measured NT-proBNP categories",
  "- Model C: predicted NT-proBNP categories from the recalibrated model",
  "",
  "Odds ratios are $\\exp(a_j)$ relative to the reference. Firth logistic regression is also fit to reduce small-sample bias and mitigate separation; interpretation of coefficients and odds ratios is the same.",
  "",
  "## Continuous spline models",
  "To visualize continuous associations, we fit restricted cubic spline logistic regression models:",
  "$$",
  "\\operatorname{logit}\\{P(outcome=1)\\} = a_0 + g(X)",
  "$$",
  "where $g(\\cdot)$ is a restricted cubic spline with 3 knots for $X$ equal to measured NT-proBNP, measured BNP, or predicted NT-proBNP. The plotted curves show odds ratios relative to the 25th percentile of $X$ using `rms::contrast`, with 95% confidence bands.",
  "",
  "## Rationale and interpretation",
  "Categorical models align with clinically used NT-proBNP thresholds and allow direct odds-ratio comparisons across risk strata. The spline models provide a nonparametric check for nonlinearity and highlight ranges where risk changes more steeply.",
  "",
  "```{r table-outcome-a}",
  "model_a_glm <- get_obj('model_a_glm')",
  "model_a_firth <- get_obj('model_a_firth')",
  "if (!is.null(model_a_glm) && !is.null(model_a_firth)) {",
  "  tbl_a <- modelsummary::modelsummary(",
  "    list('GLM' = model_a_glm, 'Firth GLM' = model_a_firth),",
  "    estimate = '{estimate} [{conf.low}, {conf.high}]',",
  "    statistic = 'p.value',",
  "    exponentiate = TRUE,",
  "    gof_map = NA,",
  "    output = 'data.frame',",
  "    shape = term ~ model + statistic",
  "  )",
  "  tbl_a <- add_reference_row(tbl_a, model_a_glm, 'NTproBNP_cat', digits = 2)",
  "  tbl_a <- tbl_a %>%",
  "    dplyr::select(-dplyr::any_of('part')) %>%",
  "    dplyr::rename(Predictor = term)",
  "  format_table(",
  "    tbl_a,",
  "    'Association between measured NT-proBNP categories and the composite outcome (odds ratios).',",
  "    digits = 2,",
  "    font_size = 8,",
  "    drop_model_type = FALSE",
  "  )",
  "} else {",
  "  cat('Outcome model A not available.\\n')",
  "}",
  "```",
  "\\pagebreak",
  "",
  "```{r table-outcome-c}",
  "model_c_glm <- get_obj('model_c_glm')",
  "model_c_firth <- get_obj('model_c_firth')",
  "if (!is.null(model_c_glm) && !is.null(model_c_firth)) {",
  "  tbl_c <- modelsummary::modelsummary(",
  "    list('GLM' = model_c_glm, 'Firth GLM' = model_c_firth),",
  "    estimate = '{estimate} [{conf.low}, {conf.high}]',",
  "    statistic = 'p.value',",
  "    exponentiate = TRUE,",
  "    gof_map = NA,",
  "    output = 'data.frame',",
  "    shape = term ~ model + statistic",
  "  )",
  "  tbl_c <- add_reference_row(tbl_c, model_c_glm, 'pred_new_median_cat', digits = 2)",
  "  tbl_c <- tbl_c %>%",
  "    dplyr::select(-dplyr::any_of('part')) %>%",
  "    dplyr::rename(Predictor = term)",
  "  format_table(",
  "    tbl_c,",
  "    'Association between predicted NT-proBNP categories (recalibrated model) and the composite outcome (odds ratios).',",
  "    digits = 2,",
  "    font_size = 8,",
  "    drop_model_type = FALSE",
  "  )",
  "} else {",
  "  cat('Outcome model C not available.\\n')",
  "}",
  "```",
  "\\pagebreak",
  "",
  "```{r fig-outcome-combined, fig.cap='Associations of measured BNP, measured NT-proBNP, and predicted NT-proBNP with outcome (spline models; shared y-axis with panel-specific x scales).'}",
  "knitr::include_graphics(file.path(params$output_dir, 'outcome_assoc_combined.png'))",
  "```",
  "",
  "```{r fig-outcome-combined-note, results='asis'}",
  "ref_vals <- get_obj('outcome_spline_ref_values')",
  "ref_n <- get_obj('outcome_spline_n')",
  "format_pgml <- function(x) {",
  "  ifelse(is.finite(x), scales::comma(round(x)), 'NA')",
  "}",
  "label_map <- c(",
  "  NTproBNP = 'NT-proBNP (measured)',",
  "  BNP = 'BNP (measured)',",
  "  pred_ntprobnp_new_median = 'NT-proBNP (predicted)'",
  ")",
  "ref_parts <- character(0)",
  "if (!is.null(ref_vals)) {",
  "  for (nm in names(label_map)) {",
  "    if (nm %in% names(ref_vals) && is.finite(ref_vals[[nm]])) {",
  "      ref_parts <- c(",
  "        ref_parts,",
  "        sprintf(",
  "          '%s: 25th percentile = %s pg/mL',",
  "          label_map[[nm]],",
  "          format_pgml(ref_vals[[nm]])",
  "        )",
  "      )",
  "    }",
  "  }",
  "}",
  "n_parts <- character(0)",
  "if (!is.null(ref_n)) {",
  "  for (nm in names(label_map)) {",
  "    if (nm %in% names(ref_n) && is.finite(ref_n[[nm]])) {",
  "      n_parts <- c(",
  "        n_parts,",
  "        sprintf(",
  "          '%s n=%s',",
  "          label_map[[nm]],",
  "          scales::comma(as.integer(ref_n[[nm]]))",
  "        )",
  "      )",
  "    }",
  "  }",
  "}",
  "ref_text <- if (length(ref_parts) > 0) {",
  "  paste(ref_parts, collapse = '; ')",
  "} else {",
  "  'Reference values unavailable.'",
  "}",
  "n_text <- if (length(n_parts) > 0) {",
  "  paste('Sample sizes for spline fits:', paste(n_parts, collapse = '; '))",
  "} else {",
  "  NULL",
  "}",
  "note_parts <- c(",
  "  '**Figure note.** Restricted cubic spline logistic regression models (3 knots; unadjusted) estimate odds ratios for the 30-day composite of MINS or vascular death. Predicted NT-proBNP values are from the recalibrated model (PaBa on log10 scale). Curves show odds ratios relative to the 25th percentile of each biomarker with 95% confidence bands.',",
  "  ref_text,",
  "  n_text",
  ")",
  "note <- paste(note_parts, collapse = ' ')",
  "cat(note, '\\n')",
  "```",
  "\\pagebreak"
)

page_break_chunk <- c(
  "",
  "```{r, results='asis'}",
  "page_break()",
  "```"
)
report_lines <- unlist(lapply(
  report_lines,
  function(line) if (identical(line, "\\pagebreak")) page_break_chunk else line
))

writeLines(report_lines, report_rmd_path)

if (requireNamespace("rmarkdown", quietly = TRUE)) {
  tryCatch(
    {
      rmarkdown::render(
        report_rmd_path,
        output_dir = CONFIG$output_dir,
        output_file = "analysis_report.docx",
        params = list(output_dir = CONFIG$output_dir),
        envir = environment(),
        quiet = FALSE
      )
      print(glue("Report saved to: {report_docx_path}"))
    },
    error = function(e) {
      print("=== REPORT RENDERING FAILED ===")
      print(e$message)
      print(e)
    }
  )
} else {
  warning("Package 'rmarkdown' is not available; skipping report generation.")
}

print("--- Finished Section 6 ---")
